"""Change expense_name-expense relationship so it uses eager loading instead

Revision ID: 0c68147ea42a
Revises: 3f112952521a
Create Date: 2025-01-18 22:52:42.881050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c68147ea42a'
down_revision: Union[str, None] = '3f112952521a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
