"""Fix updated_at timestamp arg

Revision ID: 2ed25376bb28
Revises: cd9e4d107aef
Create Date: 2025-01-20 16:00:16.638788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed25376bb28'
down_revision: Union[str, None] = 'cd9e4d107aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
