"""Change expense_name-expense relationship so it uses joined loading instead

Revision ID: 30fa667062d3
Revises: 0c68147ea42a
Create Date: 2025-01-18 23:01:08.107566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fa667062d3'
down_revision: Union[str, None] = '0c68147ea42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
