"""Change expense-expense_name relationship so it uses eager loading instead

Revision ID: 3f112952521a
Revises: cf69ee26bd35
Create Date: 2025-01-18 22:50:09.090673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f112952521a'
down_revision: Union[str, None] = 'cf69ee26bd35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
