"""Add name property in Expense Category

Revision ID: 6a83b7380417
Revises: e4185ef20228
Create Date: 2025-03-25 03:44:37.369476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a83b7380417"
down_revision: Union[str, None] = "e4185ef20228"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expense_category", sa.Column("name", sa.String(), nullable=True))

    op.execute(
        """
        UPDATE expense_category
        SET name = (SELECT name FROM category WHERE category.id = expense_category.global_category_id)
        WHERE global_category_id IS NOT NULL;
        """
    )

    op.execute(
        """
        UPDATE expense_category
        SET name = (SELECT name FROM custom_category WHERE custom_category.id = expense_category.custom_category_id)
        WHERE custom_category_id IS NOT NULL;
        """
    )

    op.execute(
        """
        UPDATE expense_category
        SET name = 'Default Category Name'
        WHERE name IS NULL;
        """
    )
    op.alter_column("expense_category", "name", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expense_category", "name")
    # ### end Alembic commands ###
