"""Add is_deleted col to user

Revision ID: 713e8e62b04b
Revises: d821d762b5ff
Create Date: 2025-01-17 23:45:04.556085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '713e8e62b04b'
down_revision: Union[str, None] = 'd821d762b5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['id'])
    op.create_unique_constraint(None, 'expense', ['id'])
    op.create_unique_constraint(None, 'expense_name', ['id'])
    op.add_column('user', sa.Column('is_deleted', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'is_deleted')
    op.drop_constraint(None, 'expense_name', type_='unique')
    op.drop_constraint(None, 'expense', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
