"""Add user_id to ExpenseName and update unique constraint

Revision ID: 80bc3c898ef2
Revises: 56e33a22390f
Create Date: 2025-01-18 19:24:08.044282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bc3c898ef2'
down_revision: Union[str, None] = '56e33a22390f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_name', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_constraint('unique_expense_name_per_category', 'expense_name', type_='unique')
    op.create_unique_constraint('unique_expense_name_per_user_and_category', 'expense_name', ['name', 'category_id', 'user_id'])
    op.create_foreign_key(None, 'expense_name', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_name', type_='foreignkey')
    op.drop_constraint('unique_expense_name_per_user_and_category', 'expense_name', type_='unique')
    op.create_unique_constraint('unique_expense_name_per_category', 'expense_name', ['name', 'category_id'])
    op.drop_column('expense_name', 'user_id')
    # ### end Alembic commands ###
