"""Remove unique constraint on Name in expense_name

Revision ID: b801f95ce4af
Revises: 48978d1b7149
Create Date: 2025-03-22 16:05:56.751082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b801f95ce4af'
down_revision: Union[str, None] = '48978d1b7149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expense_name_name_key', 'expense_name', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('expense_name_name_key', 'expense_name', ['name'])
    # ### end Alembic commands ###
