"""Add timezone attr to user model

Revision ID: cd30e8da2f27
Revises: e63309ae3a59
Create Date: 2025-01-20 17:44:30.631564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd30e8da2f27"
down_revision: Union[str, None] = "e63309ae3a59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("timezone", sa.String(), nullable=False, server_default="UTC")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "timezone")
    # ### end Alembic commands ###
