"""Fix timestamp callable arg

Revision ID: cd9e4d107aef
Revises: b5dc15f43cef
Create Date: 2025-01-20 15:52:18.128457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9e4d107aef'
down_revision: Union[str, None] = 'b5dc15f43cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
