"""Add notes attr to expense model

Revision ID: e63309ae3a59
Revises: 30fa667062d3
Create Date: 2025-01-20 14:56:24.597176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63309ae3a59'
down_revision: Union[str, None] = '30fa667062d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('note', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'note')
    # ### end Alembic commands ###
