"""Fix relationships in Category, Expense Name, Custom Category and Expense Category

Revision ID: e715d4164ef3
Revises: 43ba28d5b28d
Create Date: 2025-03-25 03:18:25.112349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e715d4164ef3'
down_revision: Union[str, None] = '43ba28d5b28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'custom_category', ['id'])
    op.create_unique_constraint(None, 'expense_category', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_category', type_='unique')
    op.drop_constraint(None, 'custom_category', type_='unique')
    # ### end Alembic commands ###
